export const CSE_QUESTION_BANK = [
  // DSA / Programming (1-30)
  { question: "What is time complexity?", topic: "DSA", category: "Technical" },
  { question: "Difference between array and linked list", topic: "DSA", category: "Technical" },
  { question: "What is a stack? Real-world example", topic: "DSA", category: "Technical" },
  { question: "Queue vs Stack", topic: "DSA", category: "Technical" },
  { question: "What is recursion?", topic: "DSA", category: "Technical" },
  { question: "Explain binary search", topic: "DSA", category: "Technical" },
  { question: "What is a hash table?", topic: "DSA", category: "Technical" },
  { question: "Collision handling techniques", topic: "DSA", category: "Technical" },
  { question: "What is a tree?", topic: "DSA", category: "Technical" },
  { question: "Binary tree vs BST", topic: "DSA", category: "Technical" },
  { question: "What is DFS and BFS?", topic: "DSA", category: "Technical" },
  { question: "What is dynamic programming?", topic: "DSA", category: "Technical" },
  { question: "Greedy vs DP", topic: "DSA", category: "Technical" },
  { question: "What is a graph?", topic: "DSA", category: "Technical" },
  { question: "Adjacency list vs matrix", topic: "DSA", category: "Technical" },
  { question: "What is sorting? Name types", topic: "DSA", category: "Technical" },
  { question: "Quick sort vs merge sort", topic: "DSA", category: "Technical" },
  { question: "What is heap?", topic: "DSA", category: "Technical" },
  { question: "What is priority queue?", topic: "DSA", category: "Technical" },
  { question: "What is backtracking?", topic: "DSA", category: "Technical" },
  { question: "What is memoization?", topic: "DSA", category: "Technical" },
  { question: "What is Big-O notation?", topic: "DSA", category: "Technical" },
  { question: "What is worst-case vs average-case?", topic: "DSA", category: "Technical" },
  { question: "What is space complexity?", topic: "DSA", category: "Technical" },
  { question: "What is recursion stack overflow?", topic: "DSA", category: "Technical" },
  { question: "What is two-pointer technique?", topic: "DSA", category: "Technical" },
  { question: "What is sliding window?", topic: "DSA", category: "Technical" },
  { question: "What is linked list cycle detection?", topic: "DSA", category: "Technical" },
  { question: "What is topological sorting?", topic: "DSA", category: "Technical" },
  { question: "What is shortest path algorithm?", topic: "DSA", category: "Technical" },

  // DBMS / OS / CN (31-55)
  { question: "What is DBMS?", topic: "DBMS", category: "Technical" },
  { question: "SQL vs NoSQL", topic: "DBMS", category: "Technical" },
  { question: "What is normalization?", topic: "DBMS", category: "Technical" },
  { question: "What is primary key?", topic: "DBMS", category: "Technical" },
  { question: "What is foreign key?", topic: "DBMS", category: "Technical" },
  { question: "What is indexing?", topic: "DBMS", category: "Technical" },
  { question: "What is transaction?", topic: "DBMS", category: "Technical" },
  { question: "ACID properties", topic: "DBMS", category: "Technical" },
  { question: "What is deadlock?", topic: "OS", category: "Technical" },
  { question: "What is process vs thread?", topic: "OS", category: "Technical" },
  { question: "What is scheduling?", topic: "OS", category: "Technical" },
  { question: "What is virtual memory?", topic: "OS", category: "Technical" },
  { question: "Paging vs segmentation", topic: "OS", category: "Technical" },
  { question: "What is cache memory?", topic: "OS", category: "Technical" },
  { question: "What is OS?", topic: "OS", category: "Technical" },
  { question: "What is TCP/IP?", topic: "CN", category: "Technical" },
  { question: "HTTP vs HTTPS", topic: "CN", category: "Technical" },
  { question: "What is DNS?", topic: "CN", category: "Technical" },
  { question: "What is IP address?", topic: "CN", category: "Technical" },
  { question: "What is subnetting?", topic: "CN", category: "Technical" },
  { question: "What is firewall?", topic: "CN", category: "Technical" },
  { question: "What is load balancing?", topic: "CN", category: "Technical" },
  { question: "What is REST API?", topic: "Web", category: "Technical" },
  { question: "What is client-server model?", topic: "Web", category: "Technical" },
  { question: "What is latency vs bandwidth?", topic: "CN", category: "Technical" },

  // Problem Solving / Logic (56-75)
  { question: "Reverse a string", topic: "PS", category: "ProblemSolving" },
  { question: "Check palindrome", topic: "PS", category: "ProblemSolving" },
  { question: "Find duplicates in array", topic: "PS", category: "ProblemSolving" },
  { question: "Fibonacci logic", topic: "PS", category: "ProblemSolving" },
  { question: "Find largest element", topic: "PS", category: "ProblemSolving" },
  { question: "Count vowels", topic: "PS", category: "ProblemSolving" },
  { question: "Remove duplicates", topic: "PS", category: "ProblemSolving" },
  { question: "Two sum problem", topic: "PS", category: "ProblemSolving" },
  { question: "Valid parentheses", topic: "PS", category: "ProblemSolving" },
  { question: "Merge two arrays", topic: "PS", category: "ProblemSolving" },
  { question: "Rotate array", topic: "PS", category: "ProblemSolving" },
  { question: "Missing number problem", topic: "PS", category: "ProblemSolving" },
  { question: "Prime number check", topic: "PS", category: "ProblemSolving" },
  { question: "Factorial logic", topic: "PS", category: "ProblemSolving" },
  { question: "Binary to decimal", topic: "PS", category: "ProblemSolving" },
  { question: "String compression", topic: "PS", category: "ProblemSolving" },
  { question: "Find second largest", topic: "PS", category: "ProblemSolving" },
  { question: "Count frequency", topic: "PS", category: "ProblemSolving" },
  { question: "Anagram check", topic: "PS", category: "ProblemSolving" },
  { question: "Subarray sum", topic: "PS", category: "ProblemSolving" },

  // Behavioral (76-100)
  { question: "Tell me about yourself", topic: "Intro", category: "Behavioral" },
  { question: "Why CSE?", topic: "Motivation", category: "Behavioral" },
  { question: "Strengths and weaknesses", topic: "Self", category: "Behavioral" },
  { question: "Biggest failure", topic: "Experience", category: "Behavioral" },
  { question: "Leadership example", topic: "Leadership", category: "Behavioral" },
  { question: "Team conflict experience", topic: "Teamwork", category: "Behavioral" },
  { question: "Handle pressure", topic: "SoftSkills", category: "Behavioral" },
  { question: "Time management", topic: "SoftSkills", category: "Behavioral" },
  { question: "Why hire you?", topic: "Value", category: "Behavioral" },
  { question: "Career goals", topic: "Future", category: "Behavioral" },
  { question: "Biggest achievement", topic: "Experience", category: "Behavioral" },
  { question: "Learn new tech quickly?", topic: "Adaptability", category: "Behavioral" },
  { question: "Handling deadlines", topic: "SoftSkills", category: "Behavioral" },
  { question: "Ethical dilemma", topic: "Ethics", category: "Behavioral" },
  { question: "Work in team vs solo", topic: "Teamwork", category: "Behavioral" },
  { question: "Feedback handling", topic: "SoftSkills", category: "Behavioral" },
  { question: "Motivation source", topic: "Self", category: "Behavioral" },
  { question: "Problem-solving approach", topic: "Logic", category: "Behavioral" },
  { question: "Mistake you learned from", topic: "Experience", category: "Behavioral" },
  { question: "Adaptability example", topic: "Adaptability", category: "Behavioral" },
  { question: "Communication skills", topic: "Communication", category: "Behavioral" },
  { question: "Difficult project", topic: "Experience", category: "Behavioral" },
  { question: "Innovation example", topic: "Thinking", category: "Behavioral" },
  { question: "How do you learn?", topic: "Adaptability", category: "Behavioral" },
  { question: "Where do you see yourself?", topic: "Future", category: "Behavioral" },
];

export const ECE_QUESTION_BANK = [
  // Core Electronics (1-30)
  { question: "What is Ohm’s Law?", topic: "Core", category: "Technical" },
  { question: "What is Kirchhoff’s Law?", topic: "Core", category: "Technical" },
  { question: "AC vs DC", topic: "Core", category: "Technical" },
  { question: "What is resistor?", topic: "Core", category: "Technical" },
  { question: "What is capacitor?", topic: "Core", category: "Technical" },
  { question: "What is inductor?", topic: "Core", category: "Technical" },
  { question: "What is diode?", topic: "Core", category: "Technical" },
  { question: "What is transistor?", topic: "Core", category: "Technical" },
  { question: "BJT vs MOSFET", topic: "Core", category: "Technical" },
  { question: "What is amplifier?", topic: "Core", category: "Technical" },
  { question: "What is gain?", topic: "Core", category: "Technical" },
  { question: "What is filter?", topic: "Core", category: "Technical" },
  { question: "Types of filters", topic: "Core", category: "Technical" },
  { question: "What is rectifier?", topic: "Core", category: "Technical" },
  { question: "Half wave vs full wave", topic: "Core", category: "Technical" },
  { question: "What is voltage regulator?", topic: "Core", category: "Technical" },
  { question: "What is impedance?", topic: "Core", category: "Technical" },
  { question: "What is resonance?", topic: "Core", category: "Technical" },
  { question: "What is power factor?", topic: "Core", category: "Technical" },
  { question: "What is signal?", topic: "Comm", category: "Technical" },
  { question: "Analog vs digital", topic: "Comm", category: "Technical" },
  { question: "What is noise?", topic: "Comm", category: "Technical" },
  { question: "What is modulation?", topic: "Comm", category: "Technical" },
  { question: "AM vs FM", topic: "Comm", category: "Technical" },
  { question: "What is bandwidth?", topic: "Comm", category: "Technical" },
  { question: "What is frequency?", topic: "Comm", category: "Technical" },
  { question: "What is waveform?", topic: "Comm", category: "Technical" },
  { question: "What is phase?", topic: "Comm", category: "Technical" },
  { question: "What is sampling theorem?", topic: "Comm", category: "Technical" },
  { question: "What is Nyquist rate?", topic: "Comm", category: "Technical" },

  // Embedded / Communication (31-55)
  { question: "What is microcontroller?", topic: "Embedded", category: "Technical" },
  { question: "Microprocessor vs microcontroller", topic: "Embedded", category: "Technical" },
  { question: "What is Arduino?", topic: "Embedded", category: "Technical" },
  { question: "What is embedded system?", topic: "Embedded", category: "Technical" },
  { question: "What is UART?", topic: "Embedded", category: "Technical" },
  { question: "SPI vs I2C", topic: "Embedded", category: "Technical" },
  { question: "What is PCB?", topic: "Embedded", category: "Technical" },
  { question: "What is RTOS?", topic: "Embedded", category: "Technical" },
  { question: "What is interrupt?", topic: "Embedded", category: "Technical" },
  { question: "What is ADC?", topic: "Embedded", category: "Technical" },
  { question: "What is DAC?", topic: "Embedded", category: "Technical" },
  { question: "What is GSM?", topic: "Comm", category: "Technical" },
  { question: "What is IoT?", topic: "Embedded", category: "Technical" },
  { question: "What is Bluetooth?", topic: "Comm", category: "Technical" },
  { question: "What is WiFi?", topic: "Comm", category: "Technical" },
  { question: "What is antenna?", topic: "Comm", category: "Technical" },
  { question: "What is propagation?", topic: "Comm", category: "Technical" },
  { question: "What is signal attenuation?", topic: "Comm", category: "Technical" },
  { question: "What is multiplexing?", topic: "Comm", category: "Technical" },
  { question: "TDM vs FDM", topic: "Comm", category: "Technical" },
  { question: "What is communication channel?", topic: "Comm", category: "Technical" },
  { question: "What is error detection?", topic: "Comm", category: "Technical" },
  { question: "What is parity bit?", topic: "Comm", category: "Technical" },
  { question: "What is encoding?", topic: "Comm", category: "Technical" },
  { question: "What is decoding?", topic: "Comm", category: "Technical" },

  // Numerical / Problem Solving (56-75)
  { question: "Calculate current using Ohm’s Law", topic: "Numerical", category: "ProblemSolving" },
  { question: "Power calculation", topic: "Numerical", category: "ProblemSolving" },
  { question: "Series vs parallel circuits", topic: "Numerical", category: "ProblemSolving" },
  { question: "Voltage division rule", topic: "Numerical", category: "ProblemSolving" },
  { question: "Current division rule", topic: "Numerical", category: "ProblemSolving" },
  { question: "Find resistance", topic: "Numerical", category: "ProblemSolving" },
  { question: "Capacitor charging", topic: "Numerical", category: "ProblemSolving" },
  { question: "Inductor behavior", topic: "Numerical", category: "ProblemSolving" },
  { question: "Frequency calculation", topic: "Numerical", category: "ProblemSolving" },
  { question: "Time period", topic: "Numerical", category: "ProblemSolving" },
  { question: "RMS value", topic: "Numerical", category: "ProblemSolving" },
  { question: "Peak value", topic: "Numerical", category: "ProblemSolving" },
  { question: "Gain calculation", topic: "Numerical", category: "ProblemSolving" },
  { question: "Efficiency calculation", topic: "Numerical", category: "ProblemSolving" },
  { question: "Signal power", topic: "Numerical", category: "ProblemSolving" },
  { question: "Bandwidth calculation", topic: "Numerical", category: "ProblemSolving" },
  { question: "SNR calculation", topic: "Numerical", category: "ProblemSolving" },
  { question: "Digital logic truth table", topic: "Numerical", category: "ProblemSolving" },
  { question: "Boolean simplification", topic: "Numerical", category: "ProblemSolving" },
  { question: "Logic gate output", topic: "Numerical", category: "ProblemSolving" },

  // Behavioral (76-100)
  { question: "Why ECE?", topic: "Motivation", category: "Behavioral" },
  { question: "Interest in electronics", topic: "Self", category: "Behavioral" },
  { question: "Practical project experience", topic: "Experience", category: "Behavioral" },
  { question: "Circuit failure handling", topic: "Experience", category: "Behavioral" },
  { question: "Lab mistakes", topic: "Experience", category: "Behavioral" },
  { question: "Teamwork example", topic: "Teamwork", category: "Behavioral" },
  { question: "Innovation in electronics", topic: "Thinking", category: "Behavioral" },
  { question: "Handling deadlines", topic: "SoftSkills", category: "Behavioral" },
  { question: "Problem-solving approach", topic: "Logic", category: "Behavioral" },
  { question: "Learning new tools", topic: "Adaptability", category: "Behavioral" },
  { question: "Strengths/weaknesses", topic: "Self", category: "Behavioral" },
  { question: "Career goals", topic: "Future", category: "Behavioral" },
  { question: "Industry interest", topic: "Motivation", category: "Behavioral" },
  { question: "Hardware vs software", topic: "Interest", category: "Behavioral" },
  { question: "Pressure handling", topic: "SoftSkills", category: "Behavioral" },
  { question: "Biggest challenge", topic: "Experience", category: "Behavioral" },
  { question: "Technical curiosity", topic: "Self", category: "Behavioral" },
  { question: "Leadership example", topic: "Leadership", category: "Behavioral" },
  { question: "Communication skills", topic: "Communication", category: "Behavioral" },
  { question: "Internship expectations", topic: "Future", category: "Behavioral" },
  { question: "Mistake learned from", topic: "Experience", category: "Behavioral" },
  { question: "Adaptability", topic: "Adaptability", category: "Behavioral" },
  { question: "Time management", topic: "SoftSkills", category: "Behavioral" },
  { question: "Why hire you?", topic: "Value", category: "Behavioral" },
  { question: "Future vision", topic: "Future", category: "Behavioral" },
];
